baseURL = "https://dev-handbook.cfapps.io/"
languageCode = "en-us"
title = "Developer Handbook"
theme = "hugo-theme-learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

# allow html on pages, for font-awesome icon support
[markup.goldmark.renderer]
unsafe= true

# theme params
[params]
disableBreadcrumb = false
disableNextPrev = true

# Show tags on sidebar
[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
weight = 30
