baseURL = "http://example.org/"
languageCode = "en-us"
title = "Developer Handbook"
theme = "hugo-theme-learn"

[params]
disableBreadcrumb = false
disableNextPrev = true

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
weight = 30
