baseURL = "https://dev-handbook.cfapps.io/"
languageCode = "en-us"
title = "Developer Handbook"
theme = "hugo-theme-learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

# allow html on pages, for font-awesome icon support
[markup.goldmark.renderer]
unsafe= true

# theme params
[params]
disableBreadcrumb = false
disableNextPrev = true

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/fombico/dev-handbook"
weight = 10
